suretez/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', index, name='index'),
    path('contact-us/', contactus, name='contactus'),
    path('blog/', blog, name='blog'),
    path('about-us/', about_us, name='about_us'),
    path("blog/<str:slug>", blogdetail, name="blog_detail"),
    path("products", products, name="products"),
    path("product/<str:slug>", product_detail, name="product_detail"),
    path('lazy_load_blogs/', lazy_load_blogs, name='lazy_load_blogs'),
]

suretez/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "SURETEZ Admin"
admin.site.site_title = "SURETEZ Admin Portal"
admin.site.index_title = "Welcome to SURETEZ Admin Portal"

urlpatterns = [
    path('backoffice/', admin.site.urls),
    path('', include('suretez.frontend.urls', namespace='frontend')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

suretez/apps/banner/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Banner(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))
    big_text = models.CharField(max_length=254, blank=True, null=True)
    small_text = models.CharField(max_length=254, blank=True, null=True)
    url = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    # owner = models.ForeignKey('user.User', on_delete=models.CASCADE)
    # kecamatan = models.ForeignKey(
    #     'kecamatan.Kecamatan', on_delete=models.SET_NULL, blank=True, null=True)
    # kelurahan = models.ForeignKey(
    #     'kelurahan.Kelurahan', on_delete=models.SET_NULL, blank=True, null=True)
    # liked_by = models.ManyToManyField('user.User', blank=True, related_name='likes_by')
    # seen_by = models.ManyToManyField('user.User', blank=True, related_name='seens_by')
    # expired = models.DateField('expired', blank=True, null=True)
    # created = AutoCreatedField()
    # price = models.IntegerField(default=0)
    # wa_number = models.CharField('Wa Number', max_length=30, blank=True, null=True)

    # def __str__(self):
    #     return self.big_text

suretez/apps/blog/models.py
from suretez.core.utils import FilenameGenerator, custom_slugify
from django.db import models
from django.utils.safestring import mark_safe



class Blog(models.Model):
    img1 =  models.ImageField("img 3:2", upload_to=FilenameGenerator(
        prefix='banner'))
    img2 =  models.ImageField("img 10:4", upload_to=FilenameGenerator(
        prefix='banner'), null=True)
    title = models.CharField(max_length=254)
    date = models.DateField(blank=True, null=True)
    short_desc = models.CharField(max_length=254, blank=True, null=True)
    long_desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField("is published", default=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    def __str__(self):
        return self.title

    def preview(self):
        return mark_safe('<a href="/blog/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Blog, self).save()

suretez/apps/contactus/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Contactus(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    subject = models.CharField(max_length=25, blank=True, null=True)
    message = models.TextField(max_length=254, blank=True, null=True)

    def __str__(self):
        return self.name

suretez/apps/menu/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=254)
    order = models.IntegerField(default=0)
    one_page_url = models.CharField(max_length=254)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

suretez/apps/portfolio/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Portfolio(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='portfolio'))
    img_detail =  models.ImageField(upload_to=FilenameGenerator(
        prefix='portfolio'))
    title = models.CharField(max_length=254, blank=True, null=True)
    sub_title = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

suretez/apps/pricing/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models

class Pricing(models.Model):
    name = models.CharField(max_length=254)
    price = models.FloatField()
    desc_list = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

suretez/apps/product/models.py
from suretez.core.utils import FilenameGenerator, custom_slugify
from django.db import models
from django.utils.safestring import mark_safe


class Product(models.Model):
    name = models.CharField("Name", max_length=255)
    banner =  models.ImageField("banner 10:4", upload_to=FilenameGenerator(
        prefix='product'), null=True)
    slug = models.CharField(unique=True, blank=True, max_length=254)
    is_active = models.BooleanField("Is Active", default=True)
    desc = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.name)
        super(Product, self).save()


class ProductPhoto(models.Model):
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='photo'))
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.product.name}-{self.id}' 

suretez/apps/service/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Service(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='service'), blank=True, null=True)
    fa_icon = models.CharField(max_length=50, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    desc = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

suretez/apps/settings/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Settings(models.Model):
    TYPE = (
        ('about_us_title', 'about_us_title'),
        ('about_us_caption', 'about_us_caption'),
        ('about_us_banner', 'about_us_banner'),
        ('about_us_description', 'about_us_description'),
        ('about_us_long_description', 'about_us_long_description'),

        # ('benefit_title', 'benefit_title'),
        # ('benefit_1_img', 'benefit_1_img'),
        # ('benefit_1_desc', 'benefit_1_desc'),
        # ('benefit_2_img', 'benefit_2_img'),
        # ('benefit_2_desc', 'benefit_2_desc'),
        # ('benefit_3_img', 'benefit_3_img'),
        # ('benefit_3_desc', 'benefit_3_desc'),

        ('blog_banner', 'blog_banner'),
        ('blog_desc', 'blog_desc'),
        ('blog_title', 'blog_title'),

        ('favicon', 'favicon'),

        ('find_product_title', 'find_product_title'),
        ('find_product_img1', 'find_product_img1'),
        ('find_product_img2', 'find_product_img2'),
        ('find_product_img3', 'find_product_img3'),
        ('find_product_img4', 'find_product_img4'),


        ('footer_logo', 'footer_logo'),
        ('footer_address_left', 'footer_address_left'),
        ('footer_bottom_text', 'footer_bottom_text'),

        ('invite_title', 'invite_title'),
        ('invite_description', 'invite_description'),
        ('invite_background', 'invite_background'),

        # ('invite_title_2', 'invite_title_2'),
        # ('invite_description_2', 'invite_description_2'),
        # ('invite_background_2', 'invite_background_2'),

        ('logo', 'logo'),

        # ('product_left_img', 'product_left_img'),
        # ('product_description', 'product_description'),
        # ('product_text_img', 'product_text_img'),
        
        
        # ('product_1_title', 'product_1_title'),
        # ('product_1_banner', 'product_1_banner'),
        # ('product_1_description', 'product_1_description'),
        # ('product_img_1', 'product_img_1'),
        # ('product_img_2', 'product_img_2'),
        # ('product_img_3', 'product_img_3'),
        # ('product_img_4', 'product_img_4'),

        # ('product_2_title', 'product_2_title'),
        # ('product_2_banner', 'product_2_banner'),
        # ('product_2_description', 'product_1_description'),
        # ('product_img_5', 'product_img_5'),
        # ('product_img_6', 'product_img_6'),
        # ('product_img_7', 'product_img_7'),
        # ('product_img_8', 'product_img_8'),
        ('products_banner', 'products_banner'),
        ('product_view_more', 'product_view_more'),

        ('seo_description', 'SEO Description'),
        ('seo_title', 'SEO Title'),
        ('seo_keywords', 'SEO Keywords'),
        ('seo_image', 'SEO Image'),

        ('testimoni_title', 'testimoni_title'),

        # socmed section
        ('socmed_big_img', 'socmed_big_img'),
        ('youtube_url', 'youtube_url' ),
        ('instagram_url', 'instagram_url' ),
        ('facebook_url', 'facebook_url' ),
        ('youtube_img', 'youtube_img' ),
        ('instagram_img', 'instagram_img' ),
        ('facebook_img', 'facebook_img' )
    )
    name = models.CharField(max_length=254, choices=TYPE, unique=True)
    text_value = models.TextField(blank=True, null=True)
    img_value =  models.ImageField(upload_to=FilenameGenerator(
        prefix='settings'), blank=True, null=True)

    def __str__(self):
        return self.name

suretez/apps/team/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Team(models.Model):
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='team'))
    name = models.CharField(max_length=254, blank=True, null=True)
    position = models.CharField(max_length=254, blank=True, null=True)
    motto = models.CharField(max_length=254, blank=True, null=True)
    fb_link = models.CharField(max_length=254, blank=True, null=True)
    twitter = models.CharField(max_length=254, blank=True, null=True)
    linkedin = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

suretez/apps/testimoni/models.py
from suretez.core.utils import FilenameGenerator
from django.db import models


class Testimoni(models.Model):
    testimony = models.TextField()
    user = models.CharField(max_length=50, null=True)
    address = models.CharField(max_length=50, null=True)
    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='testimony'), blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.testimony

suretez/frontend/forms.py
from suretez.apps.contactus.models import Contactus
from django import forms


class ContactusForm(forms.ModelForm):
    class Meta:
        model = Contactus
        fields = '__all__'

suretez/apps/banner/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/blog/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/contactus/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/menu/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/portfolio/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/pricing/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/product/views.py
from django.shortcuts import render

# Create your views here.

suretez/apps/service/views.py
from django.shortcuts import render

# Create your views here.

suretez/templates/frontend/blog-list.html
{% extends 'frontend/base.html' %}
{% block content %}

<div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div style="overflow: hidden;">
      {% if settings.blog_banner %}
      <img class="img-responsive" src="{{settings.blog_banner.img_value}}" alt="" style="display: block; width: 100%;"> 
      {% endif %}
    </div>
  </div>
</div>

<section id="blog">
  <div class="container">
    <h1 class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms" >
      {{settings.blog_title.text_value}}
    </h1>
    <div class="blog-posts">
      <div class="row list" id="posts">
        {% include 'frontend/blogs.html' %}
      </div>
      <div class="load-more wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
        <a id="lazyLoadLink" href="javascript:void(0);" data-page="2" data-link="{% url 'frontend:lazy_load_blogs' %}"
          class="btn-loadmore">View More</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}

suretez/templates/frontend/blogs-portrait.html
{% for blog in blogs %}
<div class="col-md-12 item wow fadeInUp" 
  data-wow-duration="1000ms" data-wow-delay="400ms" style="margin-bottom: 50px; padding: 0">
  <div class="post-thumb">
    <a href="{% url 'frontend:blog_detail' blog.slug %}"><img class="img-responsive" src="{{blog.img1.url}}" alt=""></a> 
  </div>
  <div class="entry-header">
    <h3><a href="{% url 'frontend:blog_detail' blog.slug %}">{{blog.title}}</a></h3>
  </div>
  <hr/>
  <div class="entry-content">
    <p style="color: rgb(49, 48, 48);">{{blog.short_desc|truncatewords:"30"}}</p>
  </div>
  <a href="{% url 'frontend:blog_detail' blog.slug %}" class="read-more" style="font-weight: bold; font-size: 1rem;">Read more</a>
</div>
{% endfor %} 

suretez/templates/frontend/blogs.html
{% for blog in blogs %}
<div class="col-sm-4 item wow fadeInUp" 
  data-wow-duration="1000ms" data-wow-delay="400ms">
  <div class="post-thumb">
    <a href="{% url 'frontend:blog_detail' blog.slug %}"><img class="img-responsive" src="{{blog.img1.url}}" alt=""></a> 
  </div>
  <div class="entry-header">
    <h3><a href="{% url 'frontend:blog_detail' blog.slug %}">{{blog.title}}</a></h3>
  </div>
  <hr/>
  <div class="entry-content">
    <p>{{blog.short_desc|truncatewords:"30"}}</p>
  </div>
  <a href="{% url 'frontend:blog_detail' blog.slug %}" class="read-more">Read more</a>
</div>
{% endfor %} 

suretez/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<div id="home-slider" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    {% for banner in banners %}
    <div class="item {% if forloop.counter == 1 %} active {% endif %}" style="height: 100% !important;">
      <img src="{{ banner.img.url }}" style="width: 100%;" />
      <!-- <div class="caption"> -->
      <!-- {% if banner.big_text %}
          <h1 class="animated fadeInLeftBig">{{ banner.big_text|safe|default:"" }}</h1>
          {% endif %}
          {% if banner.small_text %}
          <p class="animated fadeInRightBig">{{ banner.small_text|safe|default:"" }} </p>
          {% endif %} -->
      <!-- <a data-scroll class="btn btn-start animated fadeInUpBig" href="#services">Start now</a> -->
      <!-- </div> -->
    </div>
    {% endfor %}
  </div>
  <a class="left-control" href="#home-slider" data-slide="prev"><i class="fa fa-angle-left"></i></a>
  <a class="right-control" href="#home-slider" data-slide="next"><i class="fa fa-angle-right"></i></a>
  <a id="tohash" href="#services"><i class="fa fa-angle-down"></i></a>
</div>


<section id="aboutus">
  <div class="container">
    <div class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
      <div class="row wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
        <div class="col-sm-8 col-sm-offset-2">
          <h2 style="font-weight: bold; text-align: center; margin-bottom: 20px;">
            {{settings.about_us_title.text_value}}</h2>
          {{settings.about_us_description.text_value|safe}}
          <div style="text-align: center; margin: 3rem 0;">
            <a href="/#products" class="btn-hello">{{settings.about_us_caption.text_value|safe}}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section id="products" class="productsz">
  <div class="container row wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms" style="display: flex" ;>

    {% for prod in products|slice:":2" %}
    {% with forloop.counter as outer_counter %}
    <div class="col-md-6 col-sm-4 text-center" style="flex: 1;">
      <div class="w3-content product-preview">
        <div class="img-container" style="border-bottom: none; margin-bottom: 20px;">
          {% for photo in prod.productphoto_set.all %}
          <a href="{% url 'frontend:product_detail'  prod.slug %}">

            <img class="mySlides mySlides{{outer_counter}} img-display" src="{{ photo.img.url }}"
              alt=={{forloop.counter}}
              style="max-height: 100%; {% if not forloop.counter == 1 %} display: none {% endif %}">
          </a>
          {% endfor %}
        </div>
        <h5 class="prod-name">{{ prod.name }}</h5>
        <a href="{% url 'frontend:product_detail'  prod.slug %}"
          class="btn-viewmore">{{settings.product_view_more.text_value|safe}}</a>
      </div>
    </div>
    {% endwith %}
    {% endfor %}

  </div>
  </div>
</section>


{% if settings.invite_title_2.text_value %}
<section id="invite-2" class="parallax" style="background-image: url({{settings.invite_background_2.img_value}});">
  <div class="container">
    <div class="list">
      <div class="col-md-7 col-sm-12 item wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
        <h2>{{settings.invite_title_2.text_value}}</h2>
        {{ settings.invite_description_2.text_value|safe}}
      </div>
    </div>
  </div>
</section>
{% endif %}


<!-- <section id="blog">
  <div class="container">
    <h1 class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
      {{settings.blog_title.text_value}}
    </h1>
    <div class="blog-posts">
      <div class="row list" id="posts">
        {% include 'frontend/blogs.html' %}
      </div>
    </div>
  </div>
</section> -->


{% if testimonies %}
<section id="twitter">
  <div class="container">
    <h1 class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
      {{settings.testimoni_title.text_value}}
    </h1>
    <div id="twitter-carousel" class="carousel slide wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms"
      data-ride="carousel">
      <div class="carousel-inner" style="position: relative;">
        {% for test in testimonies %}
        {% if forloop.counter0|divisibleby:2 %}
        <div class="item {% if forloop.counter0 %} active {% endif %}">
          <div class="row item-wrapper">
            {% endif %}
            <div class="col-md-6" style="display: flex;">
              <img src="{{ test.img.url }}" />
              <div class="right">
                <p class="name">{{ test.user|safe }}</p>
                <p class="address">{{ test.address }}</p>
                <p class="testimony">{{ test.testimony|safe }}</p>
              </div>
            </div>
            {% if forloop.counter|divisibleby:2 %}
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
      <!-- control -->
      <a class="twitter-left-control" href="#twitter-carousel" role="button" data-slide="prev"><i
          class="fa fa-angle-left"></i></a>
      <a class="twitter-right-control" href="#twitter-carousel" role="button" data-slide="next"><i
          class="fa fa-angle-right"></i></a>
    </div>
  </div>
</section>
{% endif %}



<section id="find">
  <div class="container">
    <h1 class="wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
      {{settings.find_product_title.text_value}}
    </h1>
    <div class="row" data-wow-duration="1000ms" data-wow-delay="500ms">
      <div class="col-lg-3 col-sm-6 item">
        <img class="img" src="{{ settings.find_product_img1.img_value }} " style="max-width: 90%;" />
      </div>
      <div class="col-lg-3 col-sm-6 item">
        <img class="img" src="{{ settings.find_product_img2.img_value }}" style="max-width: 90%;" />
      </div>
      <div class="col-lg-3 col-sm-6 item">
        <img class="img" src="{{ settings.find_product_img3.img_value }}" style="max-width: 90%;" />
      </div>
      <div class="col-lg-3 col-sm-6 item">
        <img class="img" src="{{ settings.find_product_img4.img_value }}" style="max-width: 90%;" />
      </div>
    </div>
  </div>
</section>

{% if settings.invite_title %}
<section id="invite" class="parallax" style="background-image: url({{settings.invite_background.img_value}});">
  <div class="container">
    <div class="list">
      <div class="col-md-7 col-sm-12 item wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms">
        <h2>{{settings.invite_title.text_value}}</h2>
        {{ settings.invite_description.text_value|safe}}
      </div>
    </div>
  </div>
</section>
{% endif %}



{% endblock %}

{% block extra_js %}
<script>
  function currentDiv1(n) {
    showDivs(slideIndex = n);
  }

  function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides1");
    var dots = document.getElementsByClassName("demo1");
    if (n > x.length) { slideIndex = 1 }
    if (n < 1) { slideIndex = x.length }
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
    }
    x[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " w3-opacity-off";
  }

  function currentDiv2(n) {
    showDivs2(slideIndex = n);
  }

  function showDivs2(n) {
    var i;
    var x = document.getElementsByClassName("mySlides2");
    var dots = document.getElementsByClassName("demo2");
    if (n > x.length) { slideIndex = 1 }
    if (n < 1) { slideIndex = x.length }
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
    }
    x[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " w3-opacity-off";
  }
</script>
{% endblock %}

suretez/templates/frontend/product-detail.html
{% extends 'frontend/base.html' %}
{% block content %}
<section id="blog" style="padding: 0 0 20px 0 !important;">
  <div style="overflow: hidden;">
    {% if product.banner %}
    <img class="img-responsive" src="{{ product.banner.url }}" alt="" style="display: block; width: 100%;">
    {% endif %}
  </div>
  <div class="container" style="margin-top: 30px; margin-bottom: 30px;">
    <div class="row">

      <div class="col-md-4 col-sm-12 text-center">
        <div class="w3-content product-preview">
          <div class="img-container" style="height: 300px;">
            {% for photo in product.productphoto_set.all %}
            <img class="mySlides mySlide img-display" src="{{ photo.img.url }}"
              alt=={{forloop.counter}} style="max-height: 100%; {% if not forloop.counter == 1 %} display: none {% endif %}">
            {% endfor %}
          </div>

          <div class="w3-row-padding w3-section product-thumbnail">
            <div class="w3-col s2">&nbsp;</div>
            {% for photo in product.productphoto_set.all %}
            <div class="w3-col s2">
              <img class="demo w3-opacity w3-hover-opacity-off" src="{{ photo.img.url }}" style="max-width: 100%;"
                onclick="currentDiv({{ forloop.counter }})">
            </div>
            {% endfor %}
            <div class="w3-col s2">&nbsp;</div>
          </div>
        </div>
      </div>

      <div class="col-md-8 col-sm-12 wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">
        <h3 style="font-size: 2rem; font-weight: bold; text-align: center;">{{ product.name }}</h3>
        <div class="entry-content" style="
              font-size: 1em;
              letter-spacing: 0.5px;
              color: black;
              line-height: 1.5em;">
          {{product.desc|safe}}
        </div>
      </div>
    </div>
  </div>
</section>
<!--/#blog-->
{% endblock %}

{% block extra_js %}
<script>
  function currentDiv(n) {
    showDivs(slideIndex = n);
  }

  function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("demo");
    if (n > x.length) { slideIndex = 1 }
    if (n < 1) { slideIndex = x.length }
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
    }
    x[slideIndex - 1].style.display = "block";
    dots[slideIndex - 1].className += " w3-opacity-off";
  }
</script>
{% endblock %}

suretez/templates/frontend/product.html
{% extends 'frontend/base.html' %}
{% block content %}
<section id="blog" style="padding: 0 0 20px 0 !important;">
  <div style="overflow: hidden;">
    {% if settings.products_banner %}
    <img class="img-responsive" src="{{settings.products_banner.img_value}}" alt=""
      style="display: block; width: 100%;">
    {% endif %}
  </div>

  <div class="container row wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="500ms" style="display: flex; margin: 30px 0;" ;>
    {% for prod in products|slice:":2" %}
    {% with forloop.counter as outer_counter %}
    <div class="col-md-6 col-sm-4 text-center" style="flex: 1;">
      <div class="w3-content product-preview">
        <div class="img-container" style="border-bottom: none; margin-bottom: 20px;">
          {% for photo in prod.productphoto_set.all %}
          <a href="{% url 'frontend:product_detail'  prod.slug %}">
            <img class="mySlides mySlides{{outer_counter}} img-display" src="{{ photo.img.url }}"
              alt=={{forloop.counter}}
              style="max-height: 100%; {% if not forloop.counter == 1 %} display: none {% endif %}">
          </a>
          {% endfor %}
        </div>
        <h5 style="font-weight: bold; margin-top: 20px; margin-bottom: 20px;">{{ prod.name }}</h5>
        <a href="{% url 'frontend:product_detail'  prod.slug %}"
          class="btn-viewmore">{{settings.product_view_more.text_value|safe}}</a>
      </div>
    </div>
    {% endwith %}
    {% endfor %}

  </div>
  </div>
</section>
<!--/#blog-->
{% endblock %}